import '../data/schema/user_feedback.dart';

/// In-memory implementation of UserFeedbackRepository
/// This is used until the Isar schema is generated by build_runner
class InMemoryUserFeedbackRepository {
  final List<UserFeedback> _feedbackList = [];
  
  Future<void> addFeedback(String messageContent, String appPackage, String reason) async {
    final feedback = UserFeedback()
      ..messageContent = messageContent
      ..appPackage = appPackage
      ..reason = reason
      ..timestamp = DateTime.now();
    
    _feedbackList.add(feedback);
    
    // Keep only last 50 items to avoid memory issues
    if (_feedbackList.length > 50) {
      _feedbackList.removeAt(0);
    }
  }
  
  Future<List<UserFeedback>> getRecentFeedback({int limit = 15}) async {
    final endIndex = _feedbackList.length;
    final startIndex = endIndex > limit ? endIndex - limit : 0;
    return _feedbackList.sublist(startIndex, endIndex).reversed.toList();
  }
  
  Future<void> clearAll() async {
    _feedbackList.clear();
  }
}
